app = "grafana-alloy-poc"
primary_region = "arn"

[build]
  image = "grafana/alloy:v1.15.1"

[processes]
  app = "run --server.http.listen-addr=0.0.0.0:12345 /etc/alloy/config.alloy"

[http_service]
  internal_port = 12345
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
